### ISSUE TITLE
Only getting summary for interface methods

### ISSUE THREAD

**Issue by Mitsugaru** [k--kato/docomment#3]
Hey, thanks for making this plugin. I've noticed that it doesn't seem to work for interface methods though? It only generates the summary section and not detect the parameters / return value.
```csharp
/// <summary>
/// 
/// </summary>
int Generate(int level);
```

It does appear to work for the implemented method:
```csharp
/// <summary>
/// 
/// </summary>
/// <param name="level"></param>
/// <returns></returns>
public int Generate(int level)
{
}
```

I've noticed that it seems consistent for method stubs.

**Comment by k--kato** [comment]
@Mitsugaru Thanks for the code sample, helped me a lot.
